# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Submit', 'Submit Request'), ('Return', 'Return Request')], max_length=10)),
                ('operation_type', models.CharField(blank=True, choices=[('', ''), ('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=10, null=True)),
                ('trans_id', models.CharField(blank=True, max_length=6, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=14, null=True)),
                ('order_number', models.CharField(blank=True, max_length=127, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auth_result', models.CharField(blank=True, max_length=2, null=True)),
                ('result', models.CharField(blank=True, max_length=2, null=True)),
                ('error_message', models.TextField(blank=True, max_length=512, null=True)),
                ('raw_request', models.TextField(max_length=512)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
