# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systempay', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systempaytransaction',
            unique_together=set([('trans_id', 'trans_date')]),
        ),
    ]
